// <auto-generated />
using System;
using Lod.LlmGateway.Gateway.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lod.LlmGateway.Gateway.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    partial class GatewayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lod.LlmGateway.Gateway.Data.LMStudioChatRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Api")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Client")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("CloudFallbackUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GatewayRequestId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("int");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("int");

                    b.Property<bool>("LocalModelFallbackUsed")
                        .HasColumnType("bit");

                    b.Property<double?>("ModelLoadTimeSeconds")
                        .HasColumnType("float");

                    b.Property<string>("Provider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RawStatsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReasoningOutputTokens")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("RequestReceivedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RequestSentUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RequestedModel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ResponseModelInstanceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("ResponseSentUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("TimeToFirstTokenSeconds")
                        .HasColumnType("float");

                    b.Property<double?>("TokensPerSecond")
                        .HasColumnType("float");

                    b.Property<int?>("TotalOutputTokens")
                        .HasColumnType("int");

                    b.Property<string>("UpstreamResponseId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("LMStudioChat", "llm_gateway");
                });

            modelBuilder.Entity("Lod.LlmGateway.Gateway.Data.OpenAIChatCompletionDailyRollup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("CloudFallbackModelRequestCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DayUtc")
                        .HasColumnType("date");

                    b.Property<int>("FailedRequestCount")
                        .HasColumnType("int");

                    b.Property<int>("InitialModelRequestCount")
                        .HasColumnType("int");

                    b.Property<int>("LocalFallbackModelRequestCount")
                        .HasColumnType("int");

                    b.Property<double?>("NonStreamAverageTokensPerSecond")
                        .HasColumnType("float");

                    b.Property<decimal>("NonStreamCompletionCost")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("NonStreamCompletionTokens")
                        .HasColumnType("int");

                    b.Property<decimal>("NonStreamPromptCost")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("NonStreamPromptTokens")
                        .HasColumnType("int");

                    b.Property<int>("NonStreamRequestCount")
                        .HasColumnType("int");

                    b.Property<decimal>("NonStreamTotalCost")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("NonStreamTotalTokens")
                        .HasColumnType("int");

                    b.Property<int>("RequestCount")
                        .HasColumnType("int");

                    b.Property<double?>("StreamAverageTokensPerSecond")
                        .HasColumnType("float");

                    b.Property<int>("StreamCompletionTokens")
                        .HasColumnType("int");

                    b.Property<int>("StreamPromptTokens")
                        .HasColumnType("int");

                    b.Property<int>("StreamRequestCount")
                        .HasColumnType("int");

                    b.Property<int>("StreamTotalTokens")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OpenAIChatCompletionDailyRollup", "llm_gateway");
                });

            modelBuilder.Entity("Lod.LlmGateway.Gateway.Data.OpenAIChatCompletionNonStreamRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("CompletionCost")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("int");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("float");

                    b.Property<decimal?>("PromptCost")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("int");

                    b.Property<string>("RawUsageJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<double?>("TokensPerSecond")
                        .HasColumnType("float");

                    b.Property<decimal?>("TotalCost")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("int");

                    b.Property<string>("UpstreamResponseId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("OpenAIChatCompletionNonStream", "llm_gateway");
                });

            modelBuilder.Entity("Lod.LlmGateway.Gateway.Data.OpenAIChatCompletionRequestRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Api")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Client")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CloudFallbackAttemptsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CloudFallbackTierName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("CloudFallbackUsed")
                        .HasColumnType("bit");

                    b.Property<int?>("CloudFallbackWinnerIndex")
                        .HasColumnType("int");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GatewayRequestId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("int");

                    b.Property<bool>("LocalModelFallbackUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Provider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("RequestReceivedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RequestSentUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RequestedModel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ResponseModel")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("ResponseSentUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Streamed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("OpenAIChatCompletionRequest", "llm_gateway");
                });

            modelBuilder.Entity("Lod.LlmGateway.Gateway.Data.OpenAIChatCompletionStreamRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ChunkCount")
                        .HasColumnType("int");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("int");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset?>("FinalChunkSentUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FirstChunkSentUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("int");

                    b.Property<string>("RawUsageJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<double?>("TimeToFirstChunkSeconds")
                        .HasColumnType("float");

                    b.Property<double?>("TokensPerSecond")
                        .HasColumnType("float");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("OpenAIChatCompletionStream", "llm_gateway");
                });

            modelBuilder.Entity("Lod.LlmGateway.Gateway.Data.OpenAIChatCompletionNonStreamRecord", b =>
                {
                    b.HasOne("Lod.LlmGateway.Gateway.Data.OpenAIChatCompletionRequestRecord", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Lod.LlmGateway.Gateway.Data.OpenAIChatCompletionStreamRecord", b =>
                {
                    b.HasOne("Lod.LlmGateway.Gateway.Data.OpenAIChatCompletionRequestRecord", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });
#pragma warning restore 612, 618
        }
    }
}
